service: cloud-message-handler

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  memorySize: 256
  timeout: 30
  default_stage: dev
#  environment: ${file(env.yml):${opt:stage, self:provider.default_stage}}

  versionFunctions: false
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - sns:*
  #     Resource: "*"
  
functions:
  parking-status-persister:
    handler: lambdas/parking-status-persister.handler
    environment:
    events:
      - iot:
          sql: "SELECT * FROM 'updateParkingStatus'"

  parking-status-notifier:
    handler: lambdas/parking-status-notifier.handler
    environment:
    events:
      - iot:
          sql: "SELECT * FROM 'updateParkingStatus'"

  parking-status:
    handler: lambdas/parking-status.handler
    environment:
    events:
      - http: 
          path: parking/{id}
          method: get 
          private: true
          request: 
            parameters: 
              paths: 
                id: true